name: test l10n

on: [pull_request]

jobs:
  test:
    name: setup node and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: "run script and comment"
        script: |
          const path = require('path')
          const scriptPath = path.resolve('scripts/compare.js')
          const info = await require(scriptPath)

          await github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'L10N stats:\n\n' + info
          })
